# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/inwokolo/project_5/project_5.cache/wt [current_project]
set_property parent.project_path C:/Users/inwokolo/project_5/project_5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/inwokolo/project_5/project_5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  //ad/eng/users/i/n/inwokolo/Desktop/alu.v
  {//ad/eng/users/i/n/inwokolo/Desktop/bite/design sources/bin_to_dec.v}
  {//ad/eng/users/i/n/inwokolo/Desktop/bite/design sources/carry_select_adder.v}
  {//ad/eng/users/i/n/inwokolo/Desktop/bite/design sources/carry_select_subt.v}
  {//ad/eng/users/i/n/inwokolo/Desktop/bite/design sources/decoder.v}
  {//ad/eng/users/i/n/inwokolo/Desktop/bite/design sources/full_adder.v}
  //ad/eng/users/i/n/inwokolo/Desktop/half_adder.v
  {//ad/eng/users/i/n/inwokolo/Desktop/bite/design sources/negate.v}
  {//ad/eng/users/i/n/inwokolo/Desktop/bite/design sources/ripple_carry.v}
  {//ad/eng/users/i/n/inwokolo/Desktop/bite/design sources/seven_seg.v}
  {//ad/eng/users/i/n/inwokolo/Desktop/bite/design sources/system.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc //ad/eng/users/i/n/inwokolo/Desktop/bite/Nexys4DDR_Master5.xdc
set_property used_in_implementation false [get_files //ad/eng/users/i/n/inwokolo/Desktop/bite/Nexys4DDR_Master5.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top system -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_utilization_synth.rpt -pb system_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
